# Generated by Django 3.1.7 on 2021-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название точки', max_length=200)),
                ('description_short', models.TextField(help_text='Короткое описание точки', verbose_name='Короткое описание ')),
                ('description_long', models.TextField(help_text='Полное описание точки', verbose_name='Полное описание')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('long', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
