# Generated by Django 3.1.7 on 2021-04-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название картинки', max_length=200, null=True, verbose_name='Имя картинки')),
                ('sorting_priority', models.PositiveSmallIntegerField(blank=True, default=1, help_text='приоритет сортировки, по умолчанию 1', verbose_name='Сортировка')),
                ('image', models.ImageField(help_text='Изображение для модели', upload_to='')),
                ('place', models.ForeignKey(help_text='К какому месту отнести картинку', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Картинка')),
            ],
            options={
                'ordering': ['sorting_priority'],
            },
        ),
    ]
