# Generated by Django 3.1.7 on 2021-06-18 09:46

from django.db import migrations


def make_image_name_empty(apps, schema_editor):
    Image = apps.get_model('places', 'Image')
    for image in Image.objects.all():
        image.title = ''
        image.save()


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0004_auto_20210520_1310'),
    ]

    operations = [
        migrations.RunPython(make_image_name_empty)
    ]
