# Generated by Django 3.1.7 on 2021-06-21 13:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210618_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, help_text='Название картинки', max_length=200, verbose_name='Имя картинки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, help_text='Полное описание точки', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, help_text='Короткое описание точки', verbose_name='Короткое описание '),
        ),
    ]
